info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 扶뒬못
  /users:
    get:
      responses:
        "200":
          description: OK
      tags:
      - 扶뒬못
swagger: "2.0"
